### ISSUE TITLE
Poďakovanie v ENG

### ISSUE THREAD

**Issue by Ferdish** [novotnyr/rnthesis#27]
Navrhujem zmeniť názov poďakovania v ENG verzii z "Thanks" na "Acknowledgement". Je to po odbornej stránke prijateľnejší termín, ktorý sa používa aj v zahraničných publikáciách.

**Comment by novotnyr** [comment]
Dobrý nápad

Možno ešte lepšie je dať "Acknowledgements" (plurál), ako napr. http://web.stanford.edu/group/moler/theses/JWGThesis.pdf

**Comment by novotnyr** [comment]
Vyriešené cez "Acknowledgments". V prípade potreby je možné predefinovať cez

    \renewcommand\thanksname{Acknowledgments}
