### ISSUE TITLE
Čestné prehlásenie

### ISSUE THREAD

**Issue by Ferdish** [novotnyr/rnthesis#28]
Prečo nie je súčasťou šablóny? Síce sa v smernici UPJŠ nespomína ako povinná súčasť práce, ale je nepísaným pravidlom, že sa do práce zakaždým vkladá, a to aj vtedy ak je vypracovaná v inom jazyku.

**Comment by novotnyr** [comment]
Čestné vyhlásenie je podporované. Stačí pridať parameter šablóny `showhonesty`, ktorý vygeneruje stranu so štandardizovaným textom.

https://github.com/novotnyr/rnthesis/blob/master/test-cases/cestne-vyhlasenie.tex

Keďže je to voliteľná časť, štandarne sa vyhlásenie negeneruje.

Vlastný text vyhlásenia možno nastaviť cez príkaz `\vyhlasenie{...}`.
