### ISSUE TITLE
Pridať zadanie z AiS2 priamo do dokumentu

### ISSUE THREAD

**Issue by novotnyr** [novotnyr/rnthesis#9]
> AIS generuje PDF zadania a to sa da pridat priamo do dokumentu; niektori ho skenuju a tak pridavaju do PDFka, cize umoznil som to,

**Comment by novotnyr** [comment]
Preco studenti skenuju zadanie a pridavaju do PDF, ked je to ekvivalentne?

**Comment by Ferdish** [comment]
Môžte prosím upraviť šablónu tak, aby podporovala zadania dlhšie ako jedna strana?

**Comment by novotnyr** [comment]
Opravené. Štandardne sa vkladajú _všetky_ strany zadania.
